import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync, spawnSync } from 'node:child_process';
const run = (script, args) => execFileSync(process.execPath, [`benchmarks/jev/collection/${script}.mjs`, ...args], { encoding: 'utf8' });
test('blind review retains every raw case, separates decisions, and preserves disagreements', t => {
  const dir = mkdtempSync(join(tmpdir(), 'jev-review-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  mkdirSync(join(dir, 'raw'));
  const f = id => ({ id, title: 'title', category: 'logic-error', description: 'An alleged defect', attackScenario: 'A calls f', severity: 'High', confidence: 'high', affectedCode: ['C.f'], suggestedProperties: [], label: 'do-not-show' });
  writeFileSync(join(dir, 'collection.json'), JSON.stringify({ finishedAt: 'now', runs: [{ projectId: 'p', family: 'family', status: 'complete', directory: 'raw' }, { projectId: 'q', status: 'incomplete' }] }));
  writeFileSync(join(dir, 'raw/raw-findings.json'), JSON.stringify({ threats: [f('duplicate-id'), f('duplicate-id')] }));
  const out = join(dir, 'review');
  run('review', ['--collection', dir, '--out', out]);
  const casesPath = join(out, 'cases.json'), cases = JSON.parse(readFileSync(casesPath));
  assert.equal(cases.cases.length, 3);
  assert.equal(new Set(cases.cases.map(c => c.id)).size, 3);
  const packet = readFileSync(join(out, 'blind-packet.json'), 'utf8');
  assert.ok(!packet.includes('do-not-show'));
  assert.ok(cases.cases.every(c => c.label === null));
  const baseline = join(dir, 'baseline');
  run('compare', ['--cases', casesPath, '--out', baseline, '--offline']);
  assert.equal(JSON.parse(readFileSync(join(baseline, 'summary.json'))).accuracy, null);
  const aPath = join(out, 'reviewer-a.json'), bPath = join(out, 'reviewer-b.json');
  const a = JSON.parse(readFileSync(aPath)), b = JSON.parse(readFileSync(bPath));
  a.reviewer.id = 'Reviewer A'; b.reviewer.id = 'Reviewer B';
  for (const r of [a, b]) for (const c of r.cases) { c.label = c.caseId.endsWith('position') ? 'maintains' : 'distinct'; c.rationale = 'Test fixture reasoning'; }
  b.cases[0].label = 'unresolved';
  writeFileSync(aPath, JSON.stringify(a)); writeFileSync(bPath, JSON.stringify(b));
  const adjudication = join(dir, 'adjudication.json');
  run('adjudicate', ['--cases', casesPath, '--a', aPath, '--b', bPath, '--out', adjudication]);
  const result = JSON.parse(readFileSync(adjudication));
  assert.equal(result.labelingStatus, 'disputes-pending');
  assert.equal(result.cases[0].label, null);
  assert.equal(result.cases[0].votes.length, 2);
  b.reviewer.id = a.reviewer.id; writeFileSync(bPath, JSON.stringify(b));
  const rejection = spawnSync(process.execPath, ['benchmarks/jev/collection/adjudicate.mjs', '--cases', casesPath, '--a', aPath, '--b', bPath, '--out', join(dir, 'bad.json')]);
  assert.notEqual(rejection.status, 0);
});
