import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { hash } from '../benchmarks/jev/core.mjs';
test('provisional scores bind pre-comparison labels and preserve API errors in the denominator', t => {
  const dir = mkdtempSync(join(tmpdir(), 'jev-score-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const write = (p, value) => writeFileSync(join(dir, p), JSON.stringify(value));
  const dataset = { cases: [{ id: 'one', task: 'dedup', project: 'p' }, { id: 'two', task: 'dedup', project: 'p' }] };
  const labels = { createdAt: '2026-09-20T00:00:00Z', datasetSha256: hash(JSON.stringify(dataset)), reviewer: { kind: 'assistant', independent: false }, cases: [{ caseId: 'one', label: 'same', rationale: 'Same defective behavior', alternativeLabels: ['distinct'] }, { caseId: 'two', label: 'distinct', rationale: 'Separate defects', alternativeLabels: [] }] };
  const manifest = { startedAt: '2026-09-21T00:00:00Z', datasetSha256: labels.datasetSha256, provisionalLabelsSha256: hash(JSON.stringify(labels)) };
  const rows = dataset.cases.map((c, i) => ({ ...c, baseline: { prediction: 'distinct', latencyMs: 0.01 }, jev: { prediction: i ? null : 'same', latencyMs: 100 } }));
  write('cases.json', dataset); write('labels.json', labels); write('manifest.json', manifest);
  writeFileSync(join(dir, 'predictions.jsonl'), rows.map(JSON.stringify).join('\n'));
  const run = out => spawnSync(process.execPath, ['benchmarks/jev/collection/score-provisional.mjs', '--cases', join(dir, 'cases.json'), '--labels', join(dir, 'labels.json'), '--shadow', dir, '--out', join(dir, out)], { encoding: 'utf8' });
  assert.equal(run('scores.json').status, 0);
  const scores = JSON.parse(readFileSync(join(dir, 'scores.json')));
  assert.equal(scores.independentAccuracy, null);
  assert.equal(scores.tasks.dedup.jev.n, 2);
  assert.equal(scores.tasks.dedup.jev.accuracy, 0.5);
  assert.equal(scores.tasks.dedup.jev.errors, 1);
  assert.equal(scores.tasks.dedup.labelSensitivity.minimumAgreementDifference, -1);
  labels.cases[0].label = 'distinct'; write('labels.json', labels);
  assert.notEqual(run('tampered.json').status, 0);
  manifest.provisionalLabelsSha256 = hash(JSON.stringify(labels)); write('manifest.json', manifest);
  writeFileSync(join(dir, 'predictions.jsonl'), [rows[0], rows[0]].map(JSON.stringify).join('\n'));
  assert.notEqual(run('duplicated.json').status, 0);
  writeFileSync(join(dir, 'predictions.jsonl'), rows.map(JSON.stringify).join('\n'));
  labels.createdAt = '2026-09-22T00:00:00Z'; write('labels.json', labels);
  manifest.provisionalLabelsSha256 = hash(JSON.stringify(labels)); write('manifest.json', manifest);
  assert.notEqual(run('late-labels.json').status, 0);
});
