/**
 * Generate a final markdown report from the orchestrator's output.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

export interface Finding {
  id: string;
  title: string;
  severity: "Critical" | "High" | "Medium" | "Low" | "Informational";
  category: string;
  description: string;
  impact: string;
  recommendation: string;
  formallyVerified?: boolean;
  counterexample?: string;
  onChainCorrelation?: string;
}

export interface VerifiedProperty {
  name: string;
  description: string;
  status: "verified" | "violated" | "inconclusive";
  bounds: string;
  details: string;
}

export interface AuditReport {
  target: string;
  timestamp: string;
  summary: string;
  findings: Finding[];
  verifiedProperties: VerifiedProperty[];
  limitations: string[];
}

/**
 * Generate markdown report and write to output directory.
 */
export function generateReport(
  report: AuditReport,
  outputDir: string
): string {
  mkdirSync(outputDir, { recursive: true });

  const md = buildMarkdown(report);
  const reportPath = join(outputDir, "forge-proof-report.md");
  writeFileSync(reportPath, md, "utf-8");

  // Also write as JSON
  const jsonPath = join(outputDir, "forge-proof-report.json");
  writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf-8");

  return reportPath;
}

function buildMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  lines.push("# Forge Proof — Security Audit Report");
  lines.push("");
  lines.push(`**Target:** ${report.target}`);
  lines.push(`**Date:** ${report.timestamp}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(report.summary);
  lines.push("");

  // Severity counts
  const severityCounts: Record<string, number> = {};
  for (const f of report.findings) {
    severityCounts[f.severity] = (severityCounts[f.severity] || 0) + 1;
  }
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const sev of ["Critical", "High", "Medium", "Low", "Informational"]) {
    if (severityCounts[sev]) {
      lines.push(`| ${sev} | ${severityCounts[sev]} |`);
    }
  }
  lines.push("");

  // Findings
  if (report.findings.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Findings");
    lines.push("");

    for (const f of report.findings) {
      const verifiedTag = f.formallyVerified === true
        ? " (**Formally Verified**)"
        : f.formallyVerified === false
          ? ""
          : "";

      lines.push(`### ${f.id}: ${f.title}${verifiedTag}`);
      lines.push("");
      lines.push(`**Severity:** ${f.severity} | **Category:** ${f.category}`);
      lines.push("");
      lines.push("**Description:**");
      lines.push(f.description);
      lines.push("");
      lines.push("**Impact:**");
      lines.push(f.impact);
      lines.push("");
      if (f.counterexample) {
        lines.push("**Counterexample (from Halmos):**");
        lines.push("```");
        lines.push(f.counterexample);
        lines.push("```");
        lines.push("");
      }
      if (f.onChainCorrelation) {
        lines.push("**On-Chain Correlation:**");
        lines.push(f.onChainCorrelation);
        lines.push("");
      }
      lines.push("**Recommendation:**");
      lines.push(f.recommendation);
      lines.push("");
    }
  }

  // Verified Properties
  if (report.verifiedProperties.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Formally Verified Properties");
    lines.push("");
    lines.push("| Property | Status | Bounds | Details |");
    lines.push("|----------|--------|--------|---------|");
    for (const p of report.verifiedProperties) {
      const statusEmoji =
        p.status === "verified" ? "PASS" :
        p.status === "violated" ? "FAIL" : "INCONCLUSIVE";
      lines.push(
        `| ${p.name} | ${statusEmoji} | ${p.bounds} | ${p.details} |`
      );
    }
    lines.push("");
  }

  // Limitations
  if (report.limitations.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Limitations");
    lines.push("");
    for (const lim of report.limitations) {
      lines.push(`- ${lim}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by Forge Proof — AI-Powered Formal Verification*");
  lines.push("");

  return lines.join("\n");
}

/**
 * Print a compact summary to the terminal.
 */
export function printSummary(report: AuditReport): void {
  console.log("\n" + "═".repeat(60));
  console.log("  FORGE PROOF — AUDIT RESULTS");
  console.log("═".repeat(60));

  const criticals = report.findings.filter((f) => f.severity === "Critical");
  const highs = report.findings.filter((f) => f.severity === "High");
  const mediums = report.findings.filter((f) => f.severity === "Medium");
  const lows = report.findings.filter((f) => f.severity === "Low");

  console.log(
    `\n  Findings: ${criticals.length} Critical | ${highs.length} High | ${mediums.length} Medium | ${lows.length} Low`
  );

  const verified = report.verifiedProperties.filter(
    (p) => p.status === "verified"
  );
  const violated = report.verifiedProperties.filter(
    (p) => p.status === "violated"
  );
  console.log(
    `  Verification: ${verified.length} properties verified | ${violated.length} violations found`
  );

  if (criticals.length > 0) {
    console.log("\n  CRITICAL FINDINGS:");
    for (const f of criticals) {
      console.log(`    ${f.id}: ${f.title}`);
    }
  }

  if (highs.length > 0) {
    console.log("\n  HIGH FINDINGS:");
    for (const f of highs) {
      console.log(`    ${f.id}: ${f.title}`);
    }
  }

  console.log("\n" + "═".repeat(60) + "\n");
}
